### ISSUE TITLE
Always says "failed" on explore but in other shows it works fine

### ISSUE THREAD

**Issue by Dhi20071** [takkun-mint/FallGuysTools#18]

**Comment by takkun-mint** [comment]
Thank you for your report.
Our Tools uses the Creative API provided by Fall Guys DB.
It seems that a certain number of people are unable to connect to the above site under some circumstances.
If you would like, please access Fall Guys DB and check if you can search creative courses correctly.
(https://fallguys-db.pages.dev/creative)

Also, at this time we are aware of an issue where information cannot be retrieved if you are playing Creative on the first load immediately after starting Tools.
We are planning to fix this issue in a future update.

**Comment by Dhi20071** [comment]
You can change the API to cloudseeker

**Comment by takkun-mint** [comment]
Of course we know about the cloudseeker API.
It is superior to Fall Guys DB because it can take more information, but we still haven't adopted it due to frequent server failures and instability that causes extremely slow data loading speeds.
Fall Guys DB is operated by renting a big server, but cloudseeker prepares everything by himself, so it is an unavoidable factor, but we cannot migrate to it at least until the stability improves.
I also use cloudseeker a lot, so I will continue to watch this area.

**Comment by Dhi20071** [comment]
is it possible to add a setting that allows you to switch between these apis???

**Comment by Dhi20071** [comment]
btw falguysstats fix that, is it possible to fix it now??

**Comment by takkun-mint** [comment]
... If you say so much, I understand.
Let's address it in the next update.
Since we're going to make it, we'll also make the course search tool searchable by version,
 just like CloudSeeker.
