### ISSUE TITLE
Fall Guys Tools randomly crashing

### ISSUE THREAD

**Issue by Koxik-yt** [takkun-mint/FallGuysTools#25]
*Issue from yesterday, idk if it s still there*
whenever airtime or leading light starts, fallguystools crashes and gives me an error
(dont remember what it said and cant check now bc of current issue)

I was playing slimescraper in x tereme squads, when FallGuysTools randomly crashed after i finished. Ever since then I cannot open the program, and it keeps giving me the same error.
![image](https://github.com/user-attachments/assets/8ee91402-d4c8-4c99-b2ff-3e4acef3a92f)

**Comment by takkun-mint** [comment]
Thank you for your report.
It seems that an error was occurring in some knockout stages due to a specification error on the database side.
And as for the error in the Extreme Show, it seems that it was a bug that occurred at the end of the round in the Squad series, regardless of the Extreme.
At this time, Fall Guys Tools is loading from the point where it was last connected to the server when it is launched.
This is a temporary fix, but if you are experiencing a specific problem, please start the Fall Guys Tools after the next game starts.
Please note that we have already fixed the issue you mentioned.
Thank you for the information about the bug.
