### ISSUE TITLE
Unknown error

### ISSUE THREAD

**Issue by belovna7** [takkun-mint/FallGuysTools#9]
Hi, how do I fix this error?
![image](https://github.com/takkun-mint/FallGuysTools/assets/60499685/c31cdebd-bef0-43b7-9196-4a7c00db9cdb)

**Comment by takkun-mint** [comment]
Thank you for your continued patronage.
The error is that the Tools configuration file is not loading properly.
I then get a forced update when I restart,
If this does not solve the problem, please try the file in the attachment
If the problem persists, please overwrite the file in the attached file inside the bin folder of the Tools file,
If you find any files whose file name starts with "DL_", try deleting them all.

[Please overwriting.zip](https://github.com/takkun-mint/FallGuysTools/files/15208222/Please.overwriting.zip)

**Comment by belovna7** [comment]
![image](https://github.com/takkun-mint/FallGuysTools/assets/60499685/1ffede73-025a-459b-8179-ef10cb346c48)
It's still the same thing :(

**Comment by takkun-mint** [comment]
Oh, I see...
This is the first time I have seen no error output....
Looking at the source code, there is only one place where no message is output :(
I checked that part as well, and it seems that the problem occurs in the part that reads the CSV file "ToolSettings" in the bin folder and retrieves the values from it.
Just to be sure, can I ask you to check if any antivirus software is blocking the operation of this tool?
I have an acquaintance who had a case where the tool failed to work due to antivirus software....

**Comment by belovna7** [comment]
Unfortunately, disabling antivirus didn't helped. Probably will have to reinstall windows

**Comment by takkun-mint** [comment]
Oops...
In the meantime, we cannot rule out the possibility that the prerequisite software is doing something wrong, so please consider re-downloading ".Net".

**Comment by belovna7** [comment]
UPD: There's a type of error
![Снимок экрана 2024-07-11 231040](https://github.com/user-attachments/assets/8f5c141a-5e91-463f-820d-601ab9336715)

**Comment by takkun-mint** [comment]
Hello.
I still could not find the problem with Google Drive and Spreadsheets.
I'm not sure if there is some reason why the "StageInfo.csv" and "ToolSettings.csv" files are not downloading properly,
If you are using a VPN or something similar, I can't rule out the possibility that it is blocking them.
In order to find out the cause, please share the "StageInfo.csv" and "ToolSettings.csv" files in the bin file if you would like.

**Comment by belovna7** [comment]
[ToolSettings.csv](https://github.com/user-attachments/files/16201253/ToolSettings.csv)
I don't have StageInfo.csv for some reason

**Comment by takkun-mint** [comment]
Due to the specification of Tools, the system cannot be started without both StageInfo.csv and ToolSettings.csv.
(It will be a forced update.)
If the initial setup of Tools fails, the system deletes StageInfo.csv in order to insert the forced update process.
We did not see any problem with ToolSettings.csv at least.
If the initial settings still fail the next time you start the program, please back up StageInfo.csv before deleting the dialog.
At that time, if StageInfo.csv or ToolSettings.csv has "DL_" in front of its name, it would be appreciated if you could attach that as well.

**Comment by belovna7** [comment]
Yes, it was a forced update after first error, but after update it's this error again

**Comment by belovna7** [comment]
And when I press OK after error, StageInfo.csv magically disappears

**Comment by belovna7** [comment]
It works now!

**Comment by takkun-mint** [comment]
Thank you for your report!
Actually, it seems that the problem that was occurring for others was related to this issue as well.
Specifically, it seems that we were concerned about a problem in the notation of decimal points in different languages.
(In Japan and English we use a colon like 3.14, but in some countries we separate them with a comma like 3,14)
) Since I live in Japan and am inexperienced in programming, I had not taken the global into consideration at all, so when assigning the decimal point in the configuration file to the variables on each computer, a formatting error occurred due to the above difference.
I am glad you were able to solve the problem successfully.
We look forward to working with you in the future.
